# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 30082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

#  ssl:
    #    key-store: mysocket.jks
    #key-store-password: 123456
    #key-store-type: JKS
    #key-alias: mysocket

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234567

mybatis:
  mapper-locations: classpath:mapper/*.xml
 
# 日志配置
logging:
  level:
    com.das: debug
    org.springframework: warn
#clientFilePath: e:\myclient\,e:\myclient1\
#donePath: d:\myclient\,d:\myclient1\
remotePath: smb://192.168.0.19/philine/
suffixPath: /IceResults/resultbak_bak/iceResults/
clientFilePath: philishui/hefeng,philishui/lifeng,philishui/xiangmu,phiningbo/tianxiao,phiningbo/tianning
#donePath: d:\myclient\,d:\myclient1\
serverIp: 10.238.0.130
#serverIp: localhost
port: 30000
#serverFilePath: /usr/data/tranfile/pre/
#serverDonePath: /usr/data/tranfile/done/
serverFilePath: e:\myserver\
serverDonePath: d:\myserver\

#dll路径 C:\Program Files\Java\jdk1.8.0_131\jre\bin



